<?php

/**
 * @package CRM
 * @copyright CiviCRM LLC https://civicrm.org/licensing
 *
 * Generated from campaignadv/xml/schema/CRM/Campaignadv/CampaignadvInofficeLog.xml
 * DO NOT EDIT.  Generated by CRM_Core_CodeGen
 * (GenCodeChecksum:7e15f79a0c43dee7d818e5739385411a)
 */
use CRM_Campaignadv_ExtensionUtil as E;

/**
 * Database access object for the CampaignadvInofficeLog entity.
 */
class CRM_Campaignadv_DAO_CampaignadvInofficeLog extends CRM_Core_DAO {
  const EXT = E::LONG_NAME;
  const TABLE_ADDED = '';

  /**
   * Static instance to hold the table name.
   *
   * @var string
   */
  public static $_tableName = 'civicrm_campaignadv_inoffice_log';

  /**
   * Should CiviCRM log any modifications to this table in the civicrm_log table.
   *
   * @var bool
   */
  public static $_log = TRUE;

  /**
   * Soft FK to [electoral_districts_custom_table].id
   *
   * @var int
   */
  public $custom_value_id;

  /**
   * Log time as unix timestamp
   *
   * @var int
   */
  public $time;

  /**
   * Class constructor.
   */
  public function __construct() {
    $this->__table = 'civicrm_campaignadv_inoffice_log';
    parent::__construct();
  }

  /**
   * Returns localized title of this entity.
   *
   * @param bool $plural
   *   Whether to return the plural version of the title.
   */
  public static function getEntityTitle($plural = FALSE) {
    return $plural ? E::ts('Campaignadv Inoffice Logs') : E::ts('Campaignadv Inoffice Log');
  }

  /**
   * Returns all the column names of this table
   *
   * @return array
   */
  public static function &fields() {
    if (!isset(Civi::$statics[__CLASS__]['fields'])) {
      Civi::$statics[__CLASS__]['fields'] = [
        'custom_value_id' => [
          'name' => 'custom_value_id',
          'type' => CRM_Utils_Type::T_INT,
          'description' => E::ts('Soft FK to [electoral_districts_custom_table].id'),
          'required' => TRUE,
          'where' => 'civicrm_campaignadv_inoffice_log.custom_value_id',
          'table_name' => 'civicrm_campaignadv_inoffice_log',
          'entity' => 'CampaignadvInofficeLog',
          'bao' => 'CRM_Campaignadv_DAO_CampaignadvInofficeLog',
          'localizable' => 0,
          'add' => NULL,
        ],
        'time' => [
          'name' => 'time',
          'type' => CRM_Utils_Type::T_INT,
          'title' => E::ts('Time'),
          'description' => E::ts('Log time as unix timestamp'),
          'where' => 'civicrm_campaignadv_inoffice_log.time',
          'table_name' => 'civicrm_campaignadv_inoffice_log',
          'entity' => 'CampaignadvInofficeLog',
          'bao' => 'CRM_Campaignadv_DAO_CampaignadvInofficeLog',
          'localizable' => 0,
          'add' => NULL,
        ],
      ];
      CRM_Core_DAO_AllCoreTables::invoke(__CLASS__, 'fields_callback', Civi::$statics[__CLASS__]['fields']);
    }
    return Civi::$statics[__CLASS__]['fields'];
  }

  /**
   * Return a mapping from field-name to the corresponding key (as used in fields()).
   *
   * @return array
   *   Array(string $name => string $uniqueName).
   */
  public static function &fieldKeys() {
    if (!isset(Civi::$statics[__CLASS__]['fieldKeys'])) {
      Civi::$statics[__CLASS__]['fieldKeys'] = array_flip(CRM_Utils_Array::collect('name', self::fields()));
    }
    return Civi::$statics[__CLASS__]['fieldKeys'];
  }

  /**
   * Returns the names of this table
   *
   * @return string
   */
  public static function getTableName() {
    return self::$_tableName;
  }

  /**
   * Returns if this table needs to be logged
   *
   * @return bool
   */
  public function getLog() {
    return self::$_log;
  }

  /**
   * Returns the list of fields that can be imported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &import($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getImports(__CLASS__, 'campaignadv_inoffice_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of fields that can be exported
   *
   * @param bool $prefix
   *
   * @return array
   */
  public static function &export($prefix = FALSE) {
    $r = CRM_Core_DAO_AllCoreTables::getExports(__CLASS__, 'campaignadv_inoffice_log', $prefix, []);
    return $r;
  }

  /**
   * Returns the list of indices
   *
   * @param bool $localize
   *
   * @return array
   */
  public static function indices($localize = TRUE) {
    $indices = [];
    return ($localize && !empty($indices)) ? CRM_Core_DAO_AllCoreTables::multilingualize(__CLASS__, $indices) : $indices;
  }

}
